export enum CommandIds {
  ChangeWorkspace = 'changeWorkspace',
  InsertLog = 'insertLog',
  EditLogs = 'editLogs',
  RemoveLogs = 'removeLogs',
  CommentLogs = 'commentLogs',
  UncommentLogs = 'uncommentLogs',
  HighlightLogs = 'highlightLogs',
  ClearHighlights = 'clearHighlights',
  ListLogViewRefreshList = 'listLogView.refreshList',
  ListLogViewOpenFile = 'listLogView.openFile',
  ListLogViewGotoLine = 'listLogView.gotoLine',
  ListLogViewRevealFile = 'listLogView.revealFile',
  ListLogViewCopyPath = 'listLogView.copyPath',
  ListLogViewOpenContainingFolder = 'listLogView.openContainingFolder',
  ListLogViewGotoLineFromNode = 'listLogView.gotoLineFromNode',
  ListLogViewCopyLogText = 'listLogView.copyLogText',
}
